/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyCenterRouteImport } from './routes/privacy-center'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions/$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMerchantRewardConfigRouteImport } from './routes/_authenticated/merchant.reward-config'
import { Route as AuthenticatedMerchantDashboardRouteImport } from './routes/_authenticated/merchant.dashboard'
import { Route as AuthenticatedDevelopersDashboardRouteImport } from './routes/_authenticated/developers.dashboard'
import { Route as AuthenticatedCustomerWalletRouteImport } from './routes/_authenticated/customer.wallet'
import { Route as AuthenticatedCustomerTransactionsRouteImport } from './routes/_authenticated/customer.transactions'
import { Route as AuthenticatedCustomerRewardsRouteImport } from './routes/_authenticated/customer.rewards'
import { Route as AuthenticatedCustomerProfileRouteImport } from './routes/_authenticated/customer.profile'
import { Route as AuthenticatedCustomerDashboardRouteImport } from './routes/_authenticated/customer.dashboard'
import { Route as AuthenticatedAffiliatesWithdrawalsRouteImport } from './routes/_authenticated/affiliates.withdrawals'
import { Route as AuthenticatedAffiliatesNotificationsRouteImport } from './routes/_authenticated/affiliates.notifications'
import { Route as AuthenticatedAffiliatesMarketingRouteImport } from './routes/_authenticated/affiliates.marketing'
import { Route as AuthenticatedAffiliatesLinksRouteImport } from './routes/_authenticated/affiliates.links'
import { Route as AuthenticatedAffiliatesEarningsRouteImport } from './routes/_authenticated/affiliates.earnings'
import { Route as AuthenticatedAffiliatesDashboardRouteImport } from './routes/_authenticated/affiliates.dashboard'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminRoleRequestsRouteImport } from './routes/_authenticated/admin.role-requests'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminCorporateTopupRouteImport } from './routes/_authenticated/admin.corporate-topup'
import { Route as AuthenticatedAdminConsentRouteImport } from './routes/_authenticated/admin.consent'
import { Route as AuthenticatedAdminAffiliatesRouteImport } from './routes/_authenticated/admin.affiliates'
import { Route as ApiPublicRCodeRouteImport } from './routes/api/public/r.$code'
import { Route as AuthenticatedAffiliatesPromoteSlugRouteImport } from './routes/_authenticated/affiliates.promote.$slug'

const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyCenterRoute = PrivacyCenterRouteImport.update({
  id: '/privacy-center',
  path: '/privacy-center',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMerchantRewardConfigRoute =
  AuthenticatedMerchantRewardConfigRouteImport.update({
    id: '/merchant/reward-config',
    path: '/merchant/reward-config',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMerchantDashboardRoute =
  AuthenticatedMerchantDashboardRouteImport.update({
    id: '/merchant/dashboard',
    path: '/merchant/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDevelopersDashboardRoute =
  AuthenticatedDevelopersDashboardRouteImport.update({
    id: '/developers/dashboard',
    path: '/developers/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerWalletRoute =
  AuthenticatedCustomerWalletRouteImport.update({
    id: '/customer/wallet',
    path: '/customer/wallet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerTransactionsRoute =
  AuthenticatedCustomerTransactionsRouteImport.update({
    id: '/customer/transactions',
    path: '/customer/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerRewardsRoute =
  AuthenticatedCustomerRewardsRouteImport.update({
    id: '/customer/rewards',
    path: '/customer/rewards',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerProfileRoute =
  AuthenticatedCustomerProfileRouteImport.update({
    id: '/customer/profile',
    path: '/customer/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerDashboardRoute =
  AuthenticatedCustomerDashboardRouteImport.update({
    id: '/customer/dashboard',
    path: '/customer/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAffiliatesWithdrawalsRoute =
  AuthenticatedAffiliatesWithdrawalsRouteImport.update({
    id: '/affiliates/withdrawals',
    path: '/affiliates/withdrawals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAffiliatesNotificationsRoute =
  AuthenticatedAffiliatesNotificationsRouteImport.update({
    id: '/affiliates/notifications',
    path: '/affiliates/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAffiliatesMarketingRoute =
  AuthenticatedAffiliatesMarketingRouteImport.update({
    id: '/affiliates/marketing',
    path: '/affiliates/marketing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAffiliatesLinksRoute =
  AuthenticatedAffiliatesLinksRouteImport.update({
    id: '/affiliates/links',
    path: '/affiliates/links',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAffiliatesEarningsRoute =
  AuthenticatedAffiliatesEarningsRouteImport.update({
    id: '/affiliates/earnings',
    path: '/affiliates/earnings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAffiliatesDashboardRoute =
  AuthenticatedAffiliatesDashboardRouteImport.update({
    id: '/affiliates/dashboard',
    path: '/affiliates/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRoleRequestsRoute =
  AuthenticatedAdminRoleRequestsRouteImport.update({
    id: '/role-requests',
    path: '/role-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCorporateTopupRoute =
  AuthenticatedAdminCorporateTopupRouteImport.update({
    id: '/corporate-topup',
    path: '/corporate-topup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConsentRoute =
  AuthenticatedAdminConsentRouteImport.update({
    id: '/consent',
    path: '/consent',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAffiliatesRoute =
  AuthenticatedAdminAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicRCodeRoute = ApiPublicRCodeRouteImport.update({
  id: '/api/public/r/$code',
  path: '/api/public/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAffiliatesPromoteSlugRoute =
  AuthenticatedAffiliatesPromoteSlugRouteImport.update({
    id: '/affiliates/promote/$slug',
    path: '/affiliates/promote/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/privacy-center': typeof PrivacyCenterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/consent': typeof AuthenticatedAdminConsentRoute
  '/admin/corporate-topup': typeof AuthenticatedAdminCorporateTopupRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/role-requests': typeof AuthenticatedAdminRoleRequestsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/affiliates/dashboard': typeof AuthenticatedAffiliatesDashboardRoute
  '/affiliates/earnings': typeof AuthenticatedAffiliatesEarningsRoute
  '/affiliates/links': typeof AuthenticatedAffiliatesLinksRoute
  '/affiliates/marketing': typeof AuthenticatedAffiliatesMarketingRoute
  '/affiliates/notifications': typeof AuthenticatedAffiliatesNotificationsRoute
  '/affiliates/withdrawals': typeof AuthenticatedAffiliatesWithdrawalsRoute
  '/customer/dashboard': typeof AuthenticatedCustomerDashboardRoute
  '/customer/profile': typeof AuthenticatedCustomerProfileRoute
  '/customer/rewards': typeof AuthenticatedCustomerRewardsRoute
  '/customer/transactions': typeof AuthenticatedCustomerTransactionsRoute
  '/customer/wallet': typeof AuthenticatedCustomerWalletRoute
  '/developers/dashboard': typeof AuthenticatedDevelopersDashboardRoute
  '/merchant/dashboard': typeof AuthenticatedMerchantDashboardRoute
  '/merchant/reward-config': typeof AuthenticatedMerchantRewardConfigRoute
  '/affiliates/promote/$slug': typeof AuthenticatedAffiliatesPromoteSlugRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/privacy-center': typeof PrivacyCenterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions': typeof SolutionsIndexRoute
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/consent': typeof AuthenticatedAdminConsentRoute
  '/admin/corporate-topup': typeof AuthenticatedAdminCorporateTopupRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/role-requests': typeof AuthenticatedAdminRoleRequestsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/affiliates/dashboard': typeof AuthenticatedAffiliatesDashboardRoute
  '/affiliates/earnings': typeof AuthenticatedAffiliatesEarningsRoute
  '/affiliates/links': typeof AuthenticatedAffiliatesLinksRoute
  '/affiliates/marketing': typeof AuthenticatedAffiliatesMarketingRoute
  '/affiliates/notifications': typeof AuthenticatedAffiliatesNotificationsRoute
  '/affiliates/withdrawals': typeof AuthenticatedAffiliatesWithdrawalsRoute
  '/customer/dashboard': typeof AuthenticatedCustomerDashboardRoute
  '/customer/profile': typeof AuthenticatedCustomerProfileRoute
  '/customer/rewards': typeof AuthenticatedCustomerRewardsRoute
  '/customer/transactions': typeof AuthenticatedCustomerTransactionsRoute
  '/customer/wallet': typeof AuthenticatedCustomerWalletRoute
  '/developers/dashboard': typeof AuthenticatedDevelopersDashboardRoute
  '/merchant/dashboard': typeof AuthenticatedMerchantDashboardRoute
  '/merchant/reward-config': typeof AuthenticatedMerchantRewardConfigRoute
  '/affiliates/promote/$slug': typeof AuthenticatedAffiliatesPromoteSlugRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/privacy-center': typeof PrivacyCenterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/_authenticated/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/_authenticated/admin/consent': typeof AuthenticatedAdminConsentRoute
  '/_authenticated/admin/corporate-topup': typeof AuthenticatedAdminCorporateTopupRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/role-requests': typeof AuthenticatedAdminRoleRequestsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/affiliates/dashboard': typeof AuthenticatedAffiliatesDashboardRoute
  '/_authenticated/affiliates/earnings': typeof AuthenticatedAffiliatesEarningsRoute
  '/_authenticated/affiliates/links': typeof AuthenticatedAffiliatesLinksRoute
  '/_authenticated/affiliates/marketing': typeof AuthenticatedAffiliatesMarketingRoute
  '/_authenticated/affiliates/notifications': typeof AuthenticatedAffiliatesNotificationsRoute
  '/_authenticated/affiliates/withdrawals': typeof AuthenticatedAffiliatesWithdrawalsRoute
  '/_authenticated/customer/dashboard': typeof AuthenticatedCustomerDashboardRoute
  '/_authenticated/customer/profile': typeof AuthenticatedCustomerProfileRoute
  '/_authenticated/customer/rewards': typeof AuthenticatedCustomerRewardsRoute
  '/_authenticated/customer/transactions': typeof AuthenticatedCustomerTransactionsRoute
  '/_authenticated/customer/wallet': typeof AuthenticatedCustomerWalletRoute
  '/_authenticated/developers/dashboard': typeof AuthenticatedDevelopersDashboardRoute
  '/_authenticated/merchant/dashboard': typeof AuthenticatedMerchantDashboardRoute
  '/_authenticated/merchant/reward-config': typeof AuthenticatedMerchantRewardConfigRoute
  '/_authenticated/affiliates/promote/$slug': typeof AuthenticatedAffiliatesPromoteSlugRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliates'
    | '/blog'
    | '/contact'
    | '/developers'
    | '/forgot-password'
    | '/industries'
    | '/login'
    | '/privacy-center'
    | '/reset-password'
    | '/select-role'
    | '/admin'
    | '/dashboard'
    | '/auth/callback'
    | '/solutions/$slug'
    | '/solutions/'
    | '/admin/affiliates'
    | '/admin/consent'
    | '/admin/corporate-topup'
    | '/admin/dashboard'
    | '/admin/role-requests'
    | '/admin/users'
    | '/affiliates/dashboard'
    | '/affiliates/earnings'
    | '/affiliates/links'
    | '/affiliates/marketing'
    | '/affiliates/notifications'
    | '/affiliates/withdrawals'
    | '/customer/dashboard'
    | '/customer/profile'
    | '/customer/rewards'
    | '/customer/transactions'
    | '/customer/wallet'
    | '/developers/dashboard'
    | '/merchant/dashboard'
    | '/merchant/reward-config'
    | '/affiliates/promote/$slug'
    | '/api/public/r/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliates'
    | '/blog'
    | '/contact'
    | '/developers'
    | '/forgot-password'
    | '/industries'
    | '/login'
    | '/privacy-center'
    | '/reset-password'
    | '/select-role'
    | '/admin'
    | '/dashboard'
    | '/auth/callback'
    | '/solutions/$slug'
    | '/solutions'
    | '/admin/affiliates'
    | '/admin/consent'
    | '/admin/corporate-topup'
    | '/admin/dashboard'
    | '/admin/role-requests'
    | '/admin/users'
    | '/affiliates/dashboard'
    | '/affiliates/earnings'
    | '/affiliates/links'
    | '/affiliates/marketing'
    | '/affiliates/notifications'
    | '/affiliates/withdrawals'
    | '/customer/dashboard'
    | '/customer/profile'
    | '/customer/rewards'
    | '/customer/transactions'
    | '/customer/wallet'
    | '/developers/dashboard'
    | '/merchant/dashboard'
    | '/merchant/reward-config'
    | '/affiliates/promote/$slug'
    | '/api/public/r/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/affiliates'
    | '/blog'
    | '/contact'
    | '/developers'
    | '/forgot-password'
    | '/industries'
    | '/login'
    | '/privacy-center'
    | '/reset-password'
    | '/select-role'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/auth/callback'
    | '/solutions/$slug'
    | '/solutions/'
    | '/_authenticated/admin/affiliates'
    | '/_authenticated/admin/consent'
    | '/_authenticated/admin/corporate-topup'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/role-requests'
    | '/_authenticated/admin/users'
    | '/_authenticated/affiliates/dashboard'
    | '/_authenticated/affiliates/earnings'
    | '/_authenticated/affiliates/links'
    | '/_authenticated/affiliates/marketing'
    | '/_authenticated/affiliates/notifications'
    | '/_authenticated/affiliates/withdrawals'
    | '/_authenticated/customer/dashboard'
    | '/_authenticated/customer/profile'
    | '/_authenticated/customer/rewards'
    | '/_authenticated/customer/transactions'
    | '/_authenticated/customer/wallet'
    | '/_authenticated/developers/dashboard'
    | '/_authenticated/merchant/dashboard'
    | '/_authenticated/merchant/reward-config'
    | '/_authenticated/affiliates/promote/$slug'
    | '/api/public/r/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AffiliatesRoute: typeof AffiliatesRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  PrivacyCenterRoute: typeof PrivacyCenterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectRoleRoute: typeof SelectRoleRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
  ApiPublicRCodeRoute: typeof ApiPublicRCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-center': {
      id: '/privacy-center'
      path: '/privacy-center'
      fullPath: '/privacy-center'
      preLoaderRoute: typeof PrivacyCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/merchant/reward-config': {
      id: '/_authenticated/merchant/reward-config'
      path: '/merchant/reward-config'
      fullPath: '/merchant/reward-config'
      preLoaderRoute: typeof AuthenticatedMerchantRewardConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/merchant/dashboard': {
      id: '/_authenticated/merchant/dashboard'
      path: '/merchant/dashboard'
      fullPath: '/merchant/dashboard'
      preLoaderRoute: typeof AuthenticatedMerchantDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developers/dashboard': {
      id: '/_authenticated/developers/dashboard'
      path: '/developers/dashboard'
      fullPath: '/developers/dashboard'
      preLoaderRoute: typeof AuthenticatedDevelopersDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/wallet': {
      id: '/_authenticated/customer/wallet'
      path: '/customer/wallet'
      fullPath: '/customer/wallet'
      preLoaderRoute: typeof AuthenticatedCustomerWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/transactions': {
      id: '/_authenticated/customer/transactions'
      path: '/customer/transactions'
      fullPath: '/customer/transactions'
      preLoaderRoute: typeof AuthenticatedCustomerTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/rewards': {
      id: '/_authenticated/customer/rewards'
      path: '/customer/rewards'
      fullPath: '/customer/rewards'
      preLoaderRoute: typeof AuthenticatedCustomerRewardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/profile': {
      id: '/_authenticated/customer/profile'
      path: '/customer/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof AuthenticatedCustomerProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/dashboard': {
      id: '/_authenticated/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof AuthenticatedCustomerDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliates/withdrawals': {
      id: '/_authenticated/affiliates/withdrawals'
      path: '/affiliates/withdrawals'
      fullPath: '/affiliates/withdrawals'
      preLoaderRoute: typeof AuthenticatedAffiliatesWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliates/notifications': {
      id: '/_authenticated/affiliates/notifications'
      path: '/affiliates/notifications'
      fullPath: '/affiliates/notifications'
      preLoaderRoute: typeof AuthenticatedAffiliatesNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliates/marketing': {
      id: '/_authenticated/affiliates/marketing'
      path: '/affiliates/marketing'
      fullPath: '/affiliates/marketing'
      preLoaderRoute: typeof AuthenticatedAffiliatesMarketingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliates/links': {
      id: '/_authenticated/affiliates/links'
      path: '/affiliates/links'
      fullPath: '/affiliates/links'
      preLoaderRoute: typeof AuthenticatedAffiliatesLinksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliates/earnings': {
      id: '/_authenticated/affiliates/earnings'
      path: '/affiliates/earnings'
      fullPath: '/affiliates/earnings'
      preLoaderRoute: typeof AuthenticatedAffiliatesEarningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliates/dashboard': {
      id: '/_authenticated/affiliates/dashboard'
      path: '/affiliates/dashboard'
      fullPath: '/affiliates/dashboard'
      preLoaderRoute: typeof AuthenticatedAffiliatesDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/role-requests': {
      id: '/_authenticated/admin/role-requests'
      path: '/role-requests'
      fullPath: '/admin/role-requests'
      preLoaderRoute: typeof AuthenticatedAdminRoleRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/corporate-topup': {
      id: '/_authenticated/admin/corporate-topup'
      path: '/corporate-topup'
      fullPath: '/admin/corporate-topup'
      preLoaderRoute: typeof AuthenticatedAdminCorporateTopupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/consent': {
      id: '/_authenticated/admin/consent'
      path: '/consent'
      fullPath: '/admin/consent'
      preLoaderRoute: typeof AuthenticatedAdminConsentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/affiliates': {
      id: '/_authenticated/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AuthenticatedAdminAffiliatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/r/$code': {
      id: '/api/public/r/$code'
      path: '/api/public/r/$code'
      fullPath: '/api/public/r/$code'
      preLoaderRoute: typeof ApiPublicRCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/affiliates/promote/$slug': {
      id: '/_authenticated/affiliates/promote/$slug'
      path: '/affiliates/promote/$slug'
      fullPath: '/affiliates/promote/$slug'
      preLoaderRoute: typeof AuthenticatedAffiliatesPromoteSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAffiliatesRoute: typeof AuthenticatedAdminAffiliatesRoute
  AuthenticatedAdminConsentRoute: typeof AuthenticatedAdminConsentRoute
  AuthenticatedAdminCorporateTopupRoute: typeof AuthenticatedAdminCorporateTopupRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminRoleRequestsRoute: typeof AuthenticatedAdminRoleRequestsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAffiliatesRoute: AuthenticatedAdminAffiliatesRoute,
  AuthenticatedAdminConsentRoute: AuthenticatedAdminConsentRoute,
  AuthenticatedAdminCorporateTopupRoute: AuthenticatedAdminCorporateTopupRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminRoleRequestsRoute: AuthenticatedAdminRoleRequestsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAffiliatesDashboardRoute: typeof AuthenticatedAffiliatesDashboardRoute
  AuthenticatedAffiliatesEarningsRoute: typeof AuthenticatedAffiliatesEarningsRoute
  AuthenticatedAffiliatesLinksRoute: typeof AuthenticatedAffiliatesLinksRoute
  AuthenticatedAffiliatesMarketingRoute: typeof AuthenticatedAffiliatesMarketingRoute
  AuthenticatedAffiliatesNotificationsRoute: typeof AuthenticatedAffiliatesNotificationsRoute
  AuthenticatedAffiliatesWithdrawalsRoute: typeof AuthenticatedAffiliatesWithdrawalsRoute
  AuthenticatedCustomerDashboardRoute: typeof AuthenticatedCustomerDashboardRoute
  AuthenticatedCustomerProfileRoute: typeof AuthenticatedCustomerProfileRoute
  AuthenticatedCustomerRewardsRoute: typeof AuthenticatedCustomerRewardsRoute
  AuthenticatedCustomerTransactionsRoute: typeof AuthenticatedCustomerTransactionsRoute
  AuthenticatedCustomerWalletRoute: typeof AuthenticatedCustomerWalletRoute
  AuthenticatedDevelopersDashboardRoute: typeof AuthenticatedDevelopersDashboardRoute
  AuthenticatedMerchantDashboardRoute: typeof AuthenticatedMerchantDashboardRoute
  AuthenticatedMerchantRewardConfigRoute: typeof AuthenticatedMerchantRewardConfigRoute
  AuthenticatedAffiliatesPromoteSlugRoute: typeof AuthenticatedAffiliatesPromoteSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAffiliatesDashboardRoute: AuthenticatedAffiliatesDashboardRoute,
  AuthenticatedAffiliatesEarningsRoute: AuthenticatedAffiliatesEarningsRoute,
  AuthenticatedAffiliatesLinksRoute: AuthenticatedAffiliatesLinksRoute,
  AuthenticatedAffiliatesMarketingRoute: AuthenticatedAffiliatesMarketingRoute,
  AuthenticatedAffiliatesNotificationsRoute:
    AuthenticatedAffiliatesNotificationsRoute,
  AuthenticatedAffiliatesWithdrawalsRoute:
    AuthenticatedAffiliatesWithdrawalsRoute,
  AuthenticatedCustomerDashboardRoute: AuthenticatedCustomerDashboardRoute,
  AuthenticatedCustomerProfileRoute: AuthenticatedCustomerProfileRoute,
  AuthenticatedCustomerRewardsRoute: AuthenticatedCustomerRewardsRoute,
  AuthenticatedCustomerTransactionsRoute:
    AuthenticatedCustomerTransactionsRoute,
  AuthenticatedCustomerWalletRoute: AuthenticatedCustomerWalletRoute,
  AuthenticatedDevelopersDashboardRoute: AuthenticatedDevelopersDashboardRoute,
  AuthenticatedMerchantDashboardRoute: AuthenticatedMerchantDashboardRoute,
  AuthenticatedMerchantRewardConfigRoute:
    AuthenticatedMerchantRewardConfigRoute,
  AuthenticatedAffiliatesPromoteSlugRoute:
    AuthenticatedAffiliatesPromoteSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AffiliatesRoute: AffiliatesRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  PrivacyCenterRoute: PrivacyCenterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectRoleRoute: SelectRoleRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
  ApiPublicRCodeRoute: ApiPublicRCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
